name: Verilog Autograder

on:
  push:
    branches:
      - main

jobs:
  autograder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3  # Updated to v3

      # Step 2: Install Icarus Verilog
      - name: Install Icarus Verilog
        run: |
          sudo apt update
          sudo apt install -y iverilog

      # Step 3: Compile Verilog Code with predefined testbench
      - name: Compile Verilog Code
        run: |
          # Compile student's code with the instructor-provided testbench
          iverilog -o simulation_output -s discussion_tb Lab_7_v_files/*.v Modified_Codes/*.v Testbenches/*.v

      # Step 4: Run Simulation and Capture Output
      - name: Run Simulation
        run: |
          # Run the compiled simulation and save the output to results.txt
          vvp simulation_output > results.txt

      # Step 5: Show Test Results in GitHub Actions Logs
      - name: Output Simulation Results
        run: |
          cat results.txt  # Display results in the Actions log
          
      # Optional: Upload results as an artifact for later review
      - name: Upload Results
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: results-${{ github.actor }}
          path: results.txt
